### ISSUE TITLE
Prevent player movement until logged in?

### ISSUE THREAD

**Issue by Archer-Dante** [Trixtaro/TrixtaLogin#13]
Can you add such feature?
Because idk what's the point of register system if player still able to do everything without it

**Comment by Trixtaro** [comment]
Hi, it's already added!
Download last jar here [Jar](https://github.com/Trixtaro/TrixtaLogin/releases/tag/1.1)

**Comment by Archer-Dante** [comment]
Oh, yea, i tried it and it works
but i see the one difference: 1.0 from sponge website has english lines while 1.1 from here only... spanish?
and no options in config to change it back

**Comment by Archer-Dante** [comment]
tested 1.1 a bit longer
player still can moves by jumping xD
and able to use regular movement if in water (or just liquids)

**Comment by Trixtaro** [comment]
I am working right now in how change messages lines yourself to your favourite language!

**Comment by Trixtaro** [comment]
> Oh, yea, i tried it and it works
> but i see the one difference: 1.0 from sponge website has english lines while 1.1 from here only... spanish?
> and no options in config to change it back

Dowload new version 1.2 to use your custom messages at releases!

**Comment by Archer-Dante** [comment]
and what's with movement issues? ^^'

**Comment by Trixtaro** [comment]
I'll try to do the next:

When you log into server or be kicked, you will return to initial point.

**Comment by Trixtaro** [comment]
https://github.com/Trixtaro/TrixtaLogin/issues/13#issuecomment-652069003

Done! Download latest version! [Latest version here](https://github.com/Trixtaro/TrixtaLogin/releases/latest)

If you wanna support us, you can donate at paypal.me/trixtaro

**Comment by Archer-Dante** [comment]
Still buggy
If player dies due login time or login to already dead character then he got unlocked movement without /login after respawn
